language: python
sudo: false

env:
  global:
    - PIP_DEPS="pytest coveralls pytest-cov flake8"

python:
  - '3.6'

install:
- pip install -U tox-travis coverage coveralls

# download and install miniconda
- wget http://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/conda
- export PATH="$HOME/conda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Useful for debugging any issues with conda
- conda info -a

- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry conda install -c conda-forge rdkit

script: nosetests

after_success:
- coveralls
