language: python
sudo: false

env:
  global:
    - PIP_DEPS="pytest coveralls pytest-cov flake8"

python:
  - '3.6'

install:
- pip install -U tox-travis coverage coveralls
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry conda install -c rdkit rdkit

script: nosetests

after_success:
- coveralls
