language: python
sudo: no

python:
    - '3.6'

#creating conda environment:
before_install:
    #install miniconda
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p "$PWD/miniconda/"
    - export PATH="$PWD/miniconda/bin/:$PATH"
    - yes|conda update conda>/dev/null

# command to install dependencies
install:
    - yes|conda env create -f environment.yml
    - source activate pvcell
    - pip uninstall -y keras_applications
    - pip uninstall -y keras_preprocessing
    - pip uninstall -y keras
    - pip uninstall -y tensorflow
    - pip install --user tensorflow==1.10.0
    - pip install --user keras_applications==1.0.6
    - pip install --user keras_preprocessing==1.0.5
    - pip install --user keras==2.2.4
    - pip install --user coveralls

# command to run tests
script: nosetests

after_success:
    - coverage report
    - coveralls
