language: python
python:
  - "3.6"
# command to install dependencies
install:
  - travis_retry pip install $PIP_DEPS
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -e .
# command to run tests
script: nosetests
