language: python
sudo: no

python:
    - '3.6'

#creating conda environment:
before_install:
    #install miniconda
    - wget https://repo.continuum.io/archive/Anaconda2-2018.12-Linux-x86_64.sh
    - chmod +x Anaconda.sh
    - ./Anaconda.sh -b -p "$PWD/Anaconda/"
    - export PATH="$PWD/Anaconda/bin/:$PATH"
    - yes|conda update conda>/dev/null

# command to install dependencies
install:
    - yes|conda env create -f environment.yml>/dev/null
    - source activate pvc-env
    - pip uninstall -y keras_applications
    - pip uninstall -y keras_preprocessing
    - pip uninstall -y keras
    - pip uninstall -y tensorflow
    - pip install --user tensorflow==1.10.0
    - pip install --user keras_applications==1.0.6
    - pip install --user keras_preprocessing==1.0.5
    - pip install --user keras==2.2.4
    - pip install --user coveralls

# command to run tests
script: nosetests

after_success:
    - coverage report
    - coveralls
